config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             :controllers => { :registrations => "devise/custom/registrations" }

  root to: "pages#root"

  get '/home/tasks', to: 'pages#home_tasks'
  get '/home/events', to: 'pages#home_events'
  get '/common-pot', to: 'pages#common_pot'

  get '/profile', to: 'users#show'

  resources :families, only: [:new]
  get '/join-family', to: 'families#join_family'
  get '/families/create', to: 'families#create', as: 'create_family'
  get '/families/leave', to: 'families#leave', as: 'leave_family'

  resources :tasks
  get '/mark-as-recurent', to: 'tasks#mark_as_recurent'
  get '/unmark-as-recurent', to: 'tasks#unmark_as_recurent'
  get '/add-recurent', to: 'tasks#add_recurent'

  resources :competitions_tasks, only: [:update, :edit, :create]
  get '/assign-task', to: 'competitions_tasks#assign_task'
  get '/unassign-task', to: 'competitions_tasks#unassign_task'
  get '/mark-as-done', to: 'competitions_tasks#mark_as_done'
  get '/unmark-as-done', to: 'competitions_tasks#unmark_as_done'

  resources :events
  get '/assign-event', to: 'events#assign_event'
  get '/unassign-event', to: 'events#unassign_event'

  resources :competitions, only: [:index, :show, :destroy, :new, :create]

  resources :kids, only: [:index, :show, :new, :create, :update, :edit]

  get '/increase-score', to: 'scores#increase_score'
  get '/decrease-score', to: 'scores#decrease_score'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/task.rb
class Task < ApplicationRecord

  has_many :competitions_tasks
  has_many :competitions, through: :competitions_tasks


  belongs_to :user, optional: true
  belongs_to :kid

  accepts_nested_attributes_for :competitions_tasks

  validates :title, presence: true, length: { maximum: 100 }
  validates :content, length: { maximum: 200 }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :mark_as_recurent, :unmark_as_recurent]

  # GET /tasks
  def index
    query = "#{params[:task]} #{params[:user]} #{params[:kid]}".strip
    if query.empty?
      @tasks = Task.all
    else
      @tasks = Task.search_by_user_and_kid(query)
    end
  end

  # GET /tasks/1
  def show
    @competition = Competition.find(params[:competition])
    @competitions_task = CompetitionsTask.where(task: @task, competition: @competition).first

    @current_competition = current_user.family.competitions.where("end_date > ?", Time.now).first

    render layout: 'focus'
  end

  # GET /tasks/1/edit


  # GET /tasks/new
  def new
    @current_competition = current_user.family.competitions.where("end_date > ?", Time.now).first

    unless @current_competition
      redirect_back(fallback_location: root_path, alert: 'You need to start a competition.')
    end

    @task = Task.new
    @task.competitions_tasks.build
    authorize @task
    @kids = current_user.family.kids
  end

  # POST /tasks
  def create
    @task = Task.new(task_params)

    unless task_params[:kid_id].empty?
      kid_selected = Kid.find(task_params[:kid_id])
      @task.kid = kid_selected
    end

    authorize @task
    if @task.save
      redirect_to common_pot_path, notice: 'Your task has been successfully added to the common pot.'
    else
      @current_competition = current_user.family.competitions.where("end_date > ?", Time.now).first
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @current_competition = current_user.family.competitions.where("end_date > ?", Time.now).first
    @kids = current_user.family.kids
  end

  # PATCH/PUT /tasks/1
  def update
    competition = Competition.find(params[:task][:competition_id])

    if @task.update(task_params)
      redirect_to(task_path(@task, competition: competition), notice: 'Your task was successfully updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    redirect_to task_url, notice: 'Your task was successfully deleted.'
  end

  def mark_as_recurent
    @task.is_recurent = true

    if @task.save
      redirect_back(fallback_location: root_path, notice: "Task successfully marked as recurent")
    else
      redirect_back(fallback_location: root_path, alert: "Error, something went wrong")
    end
  end

  def unmark_as_recurent
    @task.is_recurent = false

    if @task.save
      redirect_back(fallback_location: root_path, notice: "Task successfully unmarked as recurent")
    else
      redirect_back(fallback_location: root_path, alert: "Error, something went wrong")
    end
  end

  def add_recurent
    @recurent_tasks = Task.joins(kid: :family).where(is_recurent: true).where(kid: {family: current_user.family})
    authorize @recurent_tasks
  end

  private

  def set_task
    @task = Task.find(params[:id])
    authorize @task
  end

  def task_params
    params.require(:task).permit(:title, :content, :kid_id, competitions_tasks_attributes: [:deadline, :competition_id])
  end
end

app/views/tasks/add_recurent.html.erb
<div class="h-100 d-flex flex-column align-items-center">
  <h2 class="heading-container mt-3 mb-4 position-relative w-100">
    Add a recurent Task
    <span class="material-symbols-outlined heading-illustration-icons">
      recycling
    </span>
  </h2>

  <div class="border-dotted border-secondary p-4 w-100 max-width-md flex-grow-1 rounded d-flex flex-column align-items-center">
    <% unless @recurent_tasks.empty? %>

      <% @recurent_tasks.each do |task| %>

        <%= link_to competitions_tasks_path(id: task), data: { turbo_method: "post" }, class: "d-flex justify-content-between border w-100 rounded-1 p-3 #{ task == @recurent_tasks.last ? '' : 'mb-3' }" do %>
          <div class="overflow-hidden flex-grow-1 me-2">
            <p class="text-truncate"><%= task.title %></p>
            <p class="fs-7"><strong>for <%= task.kid.name %></strong></p>
          </div>

          <div class="d-flex justify-content-center align-items-center">
            <span class="material-symbols-outlined" style=" font-variation-settings: 'FILL' 0, 'wght' 200;">
              add
            </span>
          </div>
        <% end %>

      <% end %>

    <% else %>
      <p class="fst-italic text-light position-absolute top-50 start-50 translate-middle">No recurent task yet</p>
    <% end %>
  </div>



</div>

app/views/tasks/edit.html.erb
<div class="d-flex flex-column align-items-center">
  <h2 class="heading-container my-4">
    Edit the task
    <span class="material-symbols-outlined heading-illustration-icons">
      task
    </span>
  </h2>

  <%= simple_form_for(@task, html: {class: "container max-width-sm px-5"}) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :title,
                  label: "title",
                  required: true,
                  autofocus: true %>
      <%= f.input :content,
                  label: "title",
                  required: true,
                  autofocus: true %>
      <%= f.association :kid,
                        collection: @kids,
                        label: "Who is it for?",
                        required: true,
                        autofocus: true %>
      <%= f.input :competition_id, as: :hidden, input_html: {value: @current_competition.id} %>
    </div>

    <div class="form-actions d-flex flex-row justify-content-around align-items-center">
      <%= f.button :submit, "Save", class: "btn btn-success my-2 mx-4" %>
      <%= link_to 'Cancel', :back, class: "btn btn-outline-danger my-2 mx-4" %>
    </div>
  <% end %>

</div>

app/views/tasks/index.html.erb
<div>
  <h1>Tasks</h1>
  <ul>
    <% @tasks.each do |task| %>
      <li>
        <%= task.title %>
        (<%= task.content %>)
        <div class="task-options">
          <% if task.user.nil? %>
            <span class="unassigned-task">Not Assigned</span>
            <%= button_to 'Add To To-Do List', assign_task_path(task), remote: true, method: :post, class: 'add-to-do-link' %>
          <% else %>
            User <%= task.user_id %> is assigned to this task.
          <% end %>
        </div>
      </li>
    <% end %>

    <% @kids_tasks.each do |kid, tasks| %>
      <h2><%= kid.name %>'s Tasks</h2>
      <% if tasks.present? %>
        <% tasks.each do |task| %>
          <li>
            <%= task.title %> (Assigned to: <%= task.kid.name %>)
            <div class="task-options">
              <% if task.user.nil? %>
                <span class="unassigned-task">Not Assigned</span>
                <%= button_to 'Add To To-Do List', assign_task_path(task), remote: true, method: :post, class: 'add-to-do-link' %>
              <% else %>
                User <%= task.user_id %> is assigned to this task.
              <% end %>
            </div>
          </li>
        <% end %>
      <% else %>
        <p>No tasks assigned to <%= kid.name %>.</p>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/tasks/new.html.erb
<div class="d-flex flex-column align-items-center">
  <div class="btn-group btn-group-toggle w-100 d-flex justify-content-center align-items-center mt-2 mb-4" data-toggle="buttons">
    <%= link_to "New Task", new_task_path, class: "btn btn-secondary", data: { btn: "New Task" }  %>
    <%= link_to "New Event", new_event_path, class: "btn btn-outline-secondary", data: { btn: "New Event" }  %>
  </div>

  <h2 class="heading-container my-4 position-relative w-100">
    Add a Task
    <span class="material-symbols-outlined heading-illustration-icons">
      task_alt
    </span>
    <div class="dropdown position-absolute body-font" style="top: 0px; right: 0px">
      <i class="dropdown-toggle material-symbols-outlined" style="font-size:2rem !important" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        more_horiz
      </i>
      <ul class="dropdown-menu rounded-1 p-3 border-secondary" style="width: 200px">
        <li><%= link_to "Add a recurent task", add_recurent_path %></li>
      </ul>
    </div>
  </h2>

  <%= simple_form_for(@task, html: {class: "container max-width-sm px-5"}) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :title,
                  label: "What's the task ?",
                  required: true,
                  autofocus: true,
                  input_html: { class: "form-control" }%>
      <%= f.input :content,
                  label: "Add some context",
                  autofocus: true,
                  input_html: { class: "form-control" }%>
      <%= f.association :kid,
                        collection: @kids,
                        label: "Who is it for?",
                        include_blank: "Select a kid",
                        required: true,
                        autofocus: true,
                        input_html: { class: "form-control" }%>


      <%= f.simple_fields_for :competitions_tasks do |m| %>
        <%= m.input :deadline,
                    as: :datetime,
                    label: "Optional deadline:",
                    required: false,
                    autofocus: true,
                    html5: true,
                    input_html: { class: "form-control",
                                  min: @current_competition.start_date.strftime('%Y-%m-%dT%H:%M'),
                                  max: @current_competition.end_date.strftime('%Y-%m-%dT%H:%M') } %>

        <%= m.input :competition_id, as: :hidden, input_html: {value: @current_competition.id} %>
      <% end %>
    </div>

    <div class="form-actions d-flex flex-row justify-content-around align-items-center">
      <%= f.button :submit, "Save", class: "btn btn-success my-2 mx-4" %>
      <%= link_to 'Cancel', common_pot_path, class: "btn btn-outline-danger my-2 mx-4" %>
    </div>
  <% end %>
</div>

app/views/tasks/show.html.erb
<div class="w-100 d-flex flex-column align-items-center">
  <h2 class="mb-3 heading-container">
    Task overview
    <span class="material-symbols-outlined heading-illustration-icons">
      search
    </span>
  </h2>

  <div class="border-dotted border-secondary p-4 rounded mb-4 d-flex flex-column align-items-center w-100 max-width-md position-relative">

    <div class="dropdown position-absolute top-0 end-0 me-2 mt-2">
      <i class="dropdown-toggle material-symbols-outlined" style="font-size:2rem !important" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        more_horiz
      </i>
      <ul class="dropdown-menu rounded-1 p-3 border-secondary" style="width: 200px">
        <li class="mb-">
          <% if @task.is_recurent %>
            <%= link_to "Unmark as recurent", unmark_as_recurent_path(id: @task) %>
          <% else %>
            <%= link_to "Mark as recurent", mark_as_recurent_path(id: @task) %>
          <% end %>
        </li>
        <% if @current_competition == @competition %>
          <li class="mt-2"><%= link_to "Edit task", edit_task_path %></li>
        <% end %>
      </ul>
    </div>


    <div class="mb-4 text-center">
      <p class="fs-3 fw-bold"><%= @task.title %></p>
      <p>for <strong><%= @task.kid.name %></strong></p>
    </div>

    <div class="w-100">
      <% if @task.content.blank? %>
        <p class="w-100 text-center fst-italic mb-3">No additional info</p>
      <% else %>
        <p class="w-100 text-center mb-3"><%= @task.content %></p>
      <% end %>
    </div>

    <p class="fs-7 me-4 fst-italic position-absolute bottom-0 end-0"><%= @task.is_recurent ? "Recurrent" : "Not recurent" %></p>

  </div>

  <div class="d-flex flex-column align-items-center border-dotted border-secondary rounded p-4 w-100 max-width-md bg-white">

    <% if @competition == @current_competition %>

      <h3 class="mb-3 w-100 text-center">In the current competition:</h3>

      <div class="d-flex flex-column align-items-center w-100 fs-5">
        <% if @competitions_task.is_done %>
          <p class="mb-3">Completed</p>
          <% if @competitions_task.user == current_user %>

            <%= link_to unmark_as_done_path(id: @competitions_task, competition_id: @competition), class: "todo-check-box" do %>
              <span class="material-symbols-outlined">
                done
              </span>
            <% end %>

          <% else %>

            <span class="material-symbols-outlined">
              done
            </span>

          <% end %>
        <% else %>
          <p class="mb-3">Not completed</p>

          <% if @competitions_task.user == current_user %>

            <%= link_to mark_as_done_path(id: @competitions_task, competition_id: @competition), class: "todo-check-box" do %>
              <span></span>
            <% end %>

          <% else %>
            <span class="material-symbols-outlined">
              close
            </span>
          <% end %>
        <% end %>
      </div>

      <div class="my-5 d-flex flex-column align-items-center">
        <p class="fs-5 ">picked by
          <% if @competitions_task.user %>
            <p><span class="fw-bold fs-1"><%= @competitions_task.user == current_user ? "You" : @competitions_task.user.first_name.capitalize %></span></p>
          <% else %>
            <p class="fs-1 fw-bold">nobody...</p>
          <% end %>
        </p>

        <% if @competitions_task.user == current_user %>
        <%= link_to "Unassign me the task", unassign_task_path(id: @competitions_task), class: "btn btn-outline-primary mt-3" %>
        <% elsif @competitions_task.user.nil? %>
          <%= link_to "Assign me the task", assign_task_path(id: @competitions_task), class: "btn btn-outline-primary mt-3" %>
        <% end %>

      </div>


      <div class="d-flex flex-column align-items-center">
        <% if @competitions_task.deadline %>
          <p class="mt-3">
            <%= link_to edit_competitions_task_path(@competitions_task), class: "material-symbols-outlined", style: "font-variation-settings: 'FILL' 1; font-size: 1rem !important" do %>
              edit
            <% end %>
            Deadline:
          </p>
          <p class="text-center"><%= @competitions_task.deadline.strftime "#{@competitions_task.deadline.day.ordinalize} %B %y at %H : %M" %></p>

        <% else %>
          <p class="fst-italic">
            <%= link_to edit_competitions_task_path(@competitions_task), class: "material-symbols-outlined", style: "font-variation-settings: 'FILL' 1; font-size: 1rem !important" do %>
              edit
            <% end %>
            No deadline
          </p>
        <% end %>
      </div>

    <% else %>
      <h3>Competition's dates</h3>
      <p><span class="fw-bold"><%= @competition.start_date.strftime "%d/%m/%y" %></span> - <span class="fw-bold"><%= @competition.end_date.strftime "%d/%m/%y" %></span></p>

      <div class="d-flex flex-column align-items-center w-100 fs-5">
        <% if @competitions_task.is_done %>
          <p class="mt-3">Completed</p>
          <span class="material-symbols-outlined">
            done
          </span>
        <% else %>
          <p class="mt-3">Not completed</p>

          <span class="material-symbols-outlined">
            close
          </span>
        <% end %>
      </div>

      <div class="my-5 d-flex flex-column align-items-center">
        <% if @competitions_task.user %>
          <p><span class="fw-bold fs-5"><%= @competitions_task.user == current_user ? "You" : @competitions_task.user.first_name.capitalize %></span></p>
          <p class="fs-5 ">picked the task</p>
        <% else %>
          <p class="fs-5 ">Nobody</p>
          <p class="fs-5 ">picked the task</p>
        <% end %>
      </div>


      <div class="d-flex flex-column align-items-center">
        <% if @competitions_task.deadline %>
          <p class="mt-3">
            Deadline:
          </p>
          <p class="text-center"><%= @competitions_task.deadline.strftime "#{@competitions_task.deadline.day.ordinalize} %B %y at %H : %M" %></p>

        <% else %>
          <p class="fst-italic">
            No deadline
          </p>
        <% end %>
      </div>
    <% end %>
  </div>
</div>