config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             :controllers => { :registrations => "devise/custom/registrations" }

  root to: "pages#root"

  get '/home/tasks', to: 'pages#home_tasks'
  get '/home/events', to: 'pages#home_events'
  get '/common-pot', to: 'pages#common_pot'

  get '/profile', to: 'users#show'

  resources :families, only: [:new]
  get '/join-family', to: 'families#join_family'
  get '/families/create', to: 'families#create', as: 'create_family'
  get '/families/leave', to: 'families#leave', as: 'leave_family'

  resources :tasks
  get '/mark-as-recurent', to: 'tasks#mark_as_recurent'
  get '/unmark-as-recurent', to: 'tasks#unmark_as_recurent'
  get '/add-recurent', to: 'tasks#add_recurent'

  resources :competitions_tasks, only: [:update, :edit, :create]
  get '/assign-task', to: 'competitions_tasks#assign_task'
  get '/unassign-task', to: 'competitions_tasks#unassign_task'
  get '/mark-as-done', to: 'competitions_tasks#mark_as_done'
  get '/unmark-as-done', to: 'competitions_tasks#unmark_as_done'

  resources :events
  get '/assign-event', to: 'events#assign_event'
  get '/unassign-event', to: 'events#unassign_event'

  resources :competitions, only: [:index, :show, :destroy, :new, :create]

  resources :kids, only: [:index, :show, :new, :create, :update, :edit]

  get '/increase-score', to: 'scores#increase_score'
  get '/decrease-score', to: 'scores#decrease_score'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events
  has_many :scores
  has_many :competitions
  has_many :tasks
  has_many :competitions_tasks

  belongs_to :family, optional: true

  has_one_attached :picture

  validates :first_name, presence: true, length: { maximum: 33 }
  validates :last_name, presence: true, length: { maximum: 33 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @family = current_user.family
    if @family

      @nb_of_competition = @family.competitions.count

      @user_number_of_competitions_won = @family.competitions.where(user: current_user).count
      @rival = @family.users.where.not(id: current_user.id).first
    end
    authorize current_user
  end
end

app/views/users/show.html.erb
<div class="user d-flex flex-column align-items-center mt-3">
  <div class="profile-picture position-relative mt-5">
    <%= image_tag "crown.svg", alt: "crown image", class: "position-absolute", style: "width: 90px; vertical-align: unset; top: -54px; left: -24px; filter: drop-shadow(1px 1px 0px rgb(0 0 0 / 0.2))" %>

    <%= render "shared/picture", user: current_user, size: "8rem", kid_or_parent: "parent" %>
  </div>
  <p class="fs-2 fw-bold"><%= "#{current_user.first_name.capitalize} #{current_user.last_name.capitalize}" %></p>
  <%# <%= link_to edit_user_registration_path, class: "d-flex align-items-center me-3 mb-4" do %>
  <div class="d-flex align-items-center me-3 mb-4" style="cursor: no-drop">
    <span class="material-symbols-outlined me-1" style="font-variation-settings: 'FILL' 1; font-size: 1rem !important">
      edit
    </span>
    <p class="btn-link fs-7"> Edit my profile </p>
  </div>
  <%# <% end %>
</div>

<h2 class="heading-container mt-4">
  Your family
  <span class="material-symbols-outlined heading-illustration-icons">
    escalator_warning
  </span>
</h2>

<div class="family border-dotted border-secondary rounded d-flex flex-column align-items-center p-3 mt-2">
  <% if @family %>
    <div class="rival d-flex flex-column align-items-center w-100">
      <h3 class="fs-5 align-self-start">
        Rival
        <span class="material-symbols-outlined heading-illustration-icons" style="font-size: 1.2rem !important; transform: translateY(1px)">
          bolt
        </span>
      </h3>

      <% if @rival %>
        <%= render "shared/picture", user: @rival, size: "4rem", kid_or_parent: "parent" %>
        <p class="mt-1"><%= "#{@rival.first_name.capitalize} #{@rival.last_name.capitalize}" %></p>
      <% else %>
        <div class="my-3">
          <p class="fs-7 fst-italic">Send the code only to your rival</p>
          <div class="copytoclipboard mt-2 w-100 d-flex justify-content-center" data-controller="clipboard">
            <%= text_field_tag(:code, @family.code, class: "text-center fs-5 bg-light border border-secondary rounded me-3", style: "width: 9rem", data: {"clipboard-target": "text"}, readonly: true) %>
            <button class="fs-3 bg-white rounded border border-secondary" style="border: none" data-action="click->clipboard#copy"><i class="ri-file-copy-line" data-clipboard-target="icon"></i></button>
          </div>
        </div>
      <% end %>
    </div>

    <div class="kids mt-3 w-100">
      <h3 class="fs-5 align-self-start">
        Kids
        <span class="material-symbols-outlined heading-illustration-icons" style="font-size: 1.2rem !important; transform: translateY(1px)">
          favorite
        </span>
      </h3>

      <% unless @family.kids.empty? %>
        <div class="kids d-flex justify-content-evenly flex-wrap">
          <% @family.kids.each do |kid| %>
            <div class="kid d-flex flex-column align-items-center">
              <%= render "shared/picture", user: kid, size: "2.2rem", kid_or_parent: "kid" %>

              <p class="mt-1"><%= kid.name.capitalize %></p>
            </div>
          <% end %>
        </div>
      <% else %>
        <div class="d-flex flex-column align-items-center my-3">
          <p class="fst-italic kids fs-7">No kid yet</p>
          <%= link_to "Add kids", new_kid_path, class: "btn btn-secondary mt-2" %>
        </div>
      <% end %>
    </div>


  <% else %>
    <div class="d-flex flex-column align-items-center m-2">
      <p class="fst-italic text-center">You need to <strong>join</strong> or <strong>create</strong> a family to have full access to the app</p>
      <%= link_to "Add you family", new_family_path, class: "btn btn-secondary mt-2" %>
    </div>
  <% end %>
</div>

<div class="d-flex flex-column align-items-center mt-5 pb-5">
  <div class="mt-3 w-100 d-flex flex-column align-items-center">
    <%# if current_user.family %>
      <%#= link_to "Leave family", leave_family_path, data: {turbo_confirm: "Are you sure you want to leave you family ?"}, class: "mb-3 btn btn-outline-danger" %>
    <%# end %>
    <%# <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "btn btn-outline-danger" %>
    <p class="btn btn-outline-danger" style="cursor: no-drop">Log out</p>
  </div>
</div>