config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             :controllers => { :registrations => "devise/custom/registrations" }

  root to: "pages#root"

  get '/home/tasks', to: 'pages#home_tasks'
  get '/home/events', to: 'pages#home_events'
  get '/common-pot', to: 'pages#common_pot'

  get '/profile', to: 'users#show'

  resources :families, only: [:new]
  get '/join-family', to: 'families#join_family'
  get '/families/create', to: 'families#create', as: 'create_family'
  get '/families/leave', to: 'families#leave', as: 'leave_family'

  resources :tasks
  get '/mark-as-recurent', to: 'tasks#mark_as_recurent'
  get '/unmark-as-recurent', to: 'tasks#unmark_as_recurent'
  get '/add-recurent', to: 'tasks#add_recurent'

  resources :competitions_tasks, only: [:update, :edit, :create]
  get '/assign-task', to: 'competitions_tasks#assign_task'
  get '/unassign-task', to: 'competitions_tasks#unassign_task'
  get '/mark-as-done', to: 'competitions_tasks#mark_as_done'
  get '/unmark-as-done', to: 'competitions_tasks#unmark_as_done'

  resources :events
  get '/assign-event', to: 'events#assign_event'
  get '/unassign-event', to: 'events#unassign_event'

  resources :competitions, only: [:index, :show, :destroy, :new, :create]

  resources :kids, only: [:index, :show, :new, :create, :update, :edit]

  get '/increase-score', to: 'scores#increase_score'
  get '/decrease-score', to: 'scores#decrease_score'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_flashes_absolute.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1 alert-absolute shadow-sm" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1 alert-absolute shadow-sm" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header class="header d-flex justify-content-between align-items-center shadow-sm position-relative branded-header">
  <%= image_tag "the-favorite-logo-svg.svg", alt: "the favorite logo", class: "d-flex flex-column align-items-center",style: "width: 147.937px; height: 40px;" %>

  <div class="d-flex">

    <% unless browser.device.mobile? %>
      <nav class="d-flex justify-content-around p-0" style="font-variation-settings: 'FILL' 0, 'wght' 200">
        <div class="d-flex justify-content-around p-0 max-width-lg w-100">
          <%= link_to home_tasks_path, class: "nav-el on-active d-flex align-items-center my-1" do %>
            <span class="material-symbols-outlined" style="font-size: 32px !important;">
              home
            </span>
            <p class="fs-7">home</p>
          <% end %>

          <%= link_to competitions_path, class: "nav-el on-active d-flex align-items-center my-1" do %>
            <span class="material-symbols-outlined" style="font-size: 32px !important;">
              trophy
            </span>
            <p class="fs-7">Score</p>
          <% end %>

          <%= link_to common_pot_path, class: "nav-el on-active d-flex align-items-center my-1" do %>
            <span class="material-symbols-outlined" style="font-size: 32px !important;">
              inventory_2
            </span>
            <p class="fs-7">Pot</p>
          <% end %>

          <%= link_to kids_path, class: "nav-el on-active d-flex align-items-center my-1" do %>
            <span class="material-symbols-outlined" style="font-size: 32px !important;">
              child_care
            </span>
            <p class="fs-7">Kids</p>
          <% end %>

          <%= link_to new_task_path, class: "btn btn-secondary nav-el on-active d-flex align-items-center my-1" do %>
            <span class="material-symbols-outlined" style="font-size: 32px !important;">
              add_circle
            </span>
            <p class="fs-7">Add</p>
          <% end %>
        </div>
      </nav>
    <% end %>

    <%= link_to profile_path, class: "ms-5 on-active d-flex flex-column align-items-center my-1" do %>
      <div class="d-flex justify-content-center align-items-center" style="height: 40px;">

        <%= render "shared/picture", user: current_user, size: "30px", kid_or_parent: "parent" %>
      </div>
    <% end %>
  </div>
</header>

app/views/shared/_navbar.html.erb
<nav class="navbar d-flex justify-content-around p-0" style="font-variation-settings: 'FILL' 0, 'wght' 200">

  <div class="d-flex justify-content-around p-0 max-width-lg w-100">
    <%= link_to home_tasks_path, class: "on-active d-flex flex-column align-items-center my-1 #{'nav-active-link' if (current_page?(home_tasks_path) || current_page?(home_events_path))}" do %>
      <span class="material-symbols-outlined">
        home
      </span>
      <p class="fs-7">home</p>
    <% end %>

    <%= link_to competitions_path, class: "on-active d-flex flex-column align-items-center my-1 #{'nav-active-link' if current_page?(competitions_path)}" do %>
      <span class="material-symbols-outlined">
        trophy
      </span>
      <p class="fs-7">score</p>
    <% end %>

    <%= link_to new_task_path, class: "on-active d-flex flex-column align-items-center my-1 #{'nav-active-link' if current_page?(new_task_path)}" do %>
      <span class="material-symbols-outlined">
        add_circle
      </span>
      <p class="fs-7">add</p>
    <% end %>

    <%= link_to common_pot_path, class: "on-active d-flex flex-column align-items-center my-1 #{'nav-active-link' if current_page?(common_pot_path)}" do %>
      <span class="material-symbols-outlined">
        inventory_2
      </span>
      <p class="fs-7">pot</p>
    <% end %>

    <%= link_to kids_path, class: "on-active d-flex flex-column align-items-center my-1 #{'nav-active-link' if current_page?(kids_path)}" do %>
      <span class="material-symbols-outlined">
        child_care
      </span>
      <p class="fs-7">kids</p>
    <% end %>
  </div>

</nav>

app/views/shared/_no_current_competition.html.erb
<div class="position-absolute top-50 start-50 translate-middle d-flex align-items-center flex-column">
  <p class="fst-italic mb-3 text-truncate">No current competition</p>
  <%= link_to "New competition", new_competition_path, class: "btn btn-secondary" %>
</div>

app/views/shared/_picture.html.erb
<% if user.picture.key %>
  <%= cl_image_tag user.picture.key, transformation: {width: "500", height: "500", crop: :thumb, gravity: :face}, class: "d-flex justify-content-center align-items-center rounded-circle", style: "width: #{size}" %>
<% else %>
  <%= image_tag "default_#{kid_or_parent}.png", class: "d-flex justify-content-center align-items-center rounded-circle", style: "width: #{size}" %>
<% end %>

app/views/shared/_user_winner.html.erb
<div class="d-flex flex-column justify-content-center align-items-center">
  <% score = user.scores.where(competition: competition).first.score %>
  <% other_user = User.where(family: user.family).where.not(id: user.id).first %>
  <% other_score = other_user.scores.where(competition: competition).first.score %>
  <p>
    <strong><%= user.first_name %></strong>
  </p>
  <div class="position-relative">
    <% if other_score < score %>
      <%= image_tag "crown.svg", alt: "user's crown", class: "position-absolute", style: "top: -2px; left: -10px; filter: drop-shadow(1px 1px 0px rgb(0 0 0 / 0.2)); width: 30px;" %>
    <% end %>
    <div class="mt-3">
      <%= render "shared/picture", user: user, size: "2.3rem", kid_or_parent: "parent" %>
    </div>
  </div>
  <p>
    <strong><%= user.scores.where(competition: competition).first.score %></strong>
  </p>
</div>