config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             :controllers => { :registrations => "devise/custom/registrations" }

  root to: "pages#root"

  get '/home/tasks', to: 'pages#home_tasks'
  get '/home/events', to: 'pages#home_events'
  get '/common-pot', to: 'pages#common_pot'

  get '/profile', to: 'users#show'

  resources :families, only: [:new]
  get '/join-family', to: 'families#join_family'
  get '/families/create', to: 'families#create', as: 'create_family'
  get '/families/leave', to: 'families#leave', as: 'leave_family'

  resources :tasks
  get '/mark-as-recurent', to: 'tasks#mark_as_recurent'
  get '/unmark-as-recurent', to: 'tasks#unmark_as_recurent'
  get '/add-recurent', to: 'tasks#add_recurent'

  resources :competitions_tasks, only: [:update, :edit, :create]
  get '/assign-task', to: 'competitions_tasks#assign_task'
  get '/unassign-task', to: 'competitions_tasks#unassign_task'
  get '/mark-as-done', to: 'competitions_tasks#mark_as_done'
  get '/unmark-as-done', to: 'competitions_tasks#unmark_as_done'

  resources :events
  get '/assign-event', to: 'events#assign_event'
  get '/unassign-event', to: 'events#unassign_event'

  resources :competitions, only: [:index, :show, :destroy, :new, :create]

  resources :kids, only: [:index, :show, :new, :create, :update, :edit]

  get '/increase-score', to: 'scores#increase_score'
  get '/decrease-score', to: 'scores#decrease_score'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :competition, optional: true
  belongs_to :kid

  validates :title, presence: true, length: { maximum: 100 }
  validates :content, length: { maximum: 200 }
  validates :date, presence: true, inclusion: { in: (Date.today..Date.today + 5.years), message: "must be after today" }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :assign_event, :unassign_event]

  def index
    query = "#{params[:event]} #{params[:user]} #{params[:kid]}".strip
    if query.empty?
      @events = Event.all
    else
      @events = Event.search_by_user_and_kid(query)
    end
  end

  def show
    @competition = Competition.find(params[:competition])
    @current_competition = current_user.family.competitions.where("end_date > ?", Time.now).first

    render layout: 'focus'
  end

  def new
    @event = Event.new
    @current_competition = current_user.family.competitions.where("end_date > ?", Time.now).first
    @kids = current_user.family.kids
    authorize @event
  end

  def create
    @event = Event.new(event_params)
    authorize @event

    @current_competition = current_user.family.competitions.where("end_date > ?", Time.now).first

    @event.date = nil if @event.date > @current_competition.end_date

    if @event.save
      redirect_to common_pot_path, notice: 'Your event has been successfully added to the common pot.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @current_competition = current_user.family.competitions.where("end_date > ?", Time.now).first
    @kids = current_user.family.kids
  end

  def update
    competition = Competition.find(params[:event][:competition_id])

    if @event.update(event_params)
      redirect_to(event_path(@event, competition: competition), notice: 'Your event was successfully updated')
    else
      @current_competition = current_user.family.competitions.where("end_date > ?", Time.now).first
      @kids = current_user.family.kids
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event.destroy
    redirect_to event_url, notice: 'Your event was successfully deleted.'
  end

  def assign_event
    @current_competition = current_user.family.competitions.where("end_date > ?", Time.now).first

    if @event && @event.user.nil?
      @event.user = current_user
      @event.save!

      score = Score.where(user: current_user).where(competition: @current_competition).first
      score.score += 1
      score.save!
    end
    redirect_back(fallback_location: root_path)
  end

  def unassign_event
    @current_competition = current_user.family.competitions.where("end_date > ?", Time.now).first

    if @event && @event.user
      @event.user = nil
      @event.save!

      score = Score.where(user: current_user).where(competition: @current_competition).first
      score.score -= 1
      score.save!
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def set_event
    @event = Event.find(params[:id])
    authorize @event
  end

  def event_params
    params.require(:event).permit(:title, :content, :date, :kid_id, :competition_id)
  end
end

app/views/events/edit.html.erb
<div class="d-flex flex-column align-items-center">
  <h2 class="heading-container my-4">
    Edit the event
    <span class="material-symbols-outlined heading-illustration-icons">
      event
    </span>
  </h2>

  <%= simple_form_for(@event, html: {class: "container max-width-sm px-5"}) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :title,
                  label: "title",
                  required: true,
                  autofocus: true %>
      <%= f.input :content,
                  label: "title",
                  required: true,
                  autofocus: true %>
      <%= f.input :date,
                  as: :datetime,
                  label: "Date of the Event",
                  required: false,
                  autofocus: true,
                  html5: true,
                  input_html: { min: DateTime.current.strftime('%Y-%m-%dT%H:%M') } %>
      <%= f.association :kid,
                        collection: @kids,
                        label: "Who is it for?",
                        required: true,
                        autofocus: true %>
      <%= f.input :competition_id, as: :hidden, input_html: {value: @current_competition.id} %>

    </div>

    <div class="form-actions d-flex flex-row justify-content-around align-items-center">
      <%= f.button :submit, "Save", class: "btn btn-success my-2 mx-4" %>
      <%= link_to 'Cancel', :back, class: "btn btn-outline-danger my-2 mx-4" %>
    </div>
  <% end %>

</div>

app/views/events/index.html.erb
<div>
  <h1>Events</h1>
  <ul>
    <% @events.each do |event| %>
      <li>
        <%= event.title %>
        (<%= event.content %>)
        (<%= event.location %>)
        <div class="event-options">
          <% if event.user_id.nil? %>
            <span class="unassigned-event">Not Assigned</span>
            <%= link_to 'Add To Calendar', root_path, method: :post, class: 'add-calendar-link' %>
          <% else %>
            User <%= event.user_id %> is assigned to this event.
          <% end %>
        </div>
      </li>
    <% end %>

    <%= event.title %> (Assigned to: <%= event.kid.name %>)
            <div class="event-options">
              <% if event.user.nil? %>
                <span class="unassigned-event">Not Assigned</span>
                <%= link_to 'Add To Calendar', root_path, method: :post, class: 'add-calendar-link' %>
              <% else %>
                User <%= event.user_id %> is assigned to this event.
              <% end %>
            </div>
          </li>
        <% end %>
      <% else %>
        <p>No events assigned to <%= kid.name %>.</p>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/events/new.html.erb
<div class="d-flex flex-column align-items-center">
  <div class="btn-group btn-group-toggle w-100 d-flex justify-content-center align-items-center mt-2 mb-4" data-toggle="buttons">
    <%= link_to "New Task", new_task_path, class: "btn btn-outline-secondary", data: { btn: "New Task" }  %>
    <%= link_to "New Event", new_event_path, class: "btn btn-secondary", data: { btn: "New Event" }  %>
  </div>

  <h2 class="heading-container my-4">
    Add an Event
    <span class="material-symbols-outlined heading-illustration-icons">
      event
    </span>
  </h2>

  <%= simple_form_for(@event, html: {class: "container max-width-sm px-5"}) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :title,
                  label: "What's the event ?",
                  required: true,
                  autofocus: true %>
      <%= f.input :content,
                  label: "Add some context",
                  autofocus: true %>
      <%= f.input :date,
                  as: :datetime,
                  label: "Select a date and a time",
                  html5: true,
                  input_html: { class: "form-control",
                                min: DateTime.current },
                  required: true,
                  autofocus: true %>
      <%= f.association :kid,
                        collection: @kids,
                        label: "Who is it for?",
                        include_blank: "Select a kid",
                        required: true,
                        autofocus: true,
                        input_html: { class: "form-control" }%>

      <%= f.input :competition_id, as: :hidden, input_html: {value: @current_competition.id} %>
    </div>
    <div class="form-actions d-flex flex-row justify-content-around align-items-center">
      <%= f.button :submit, "Save", class: "btn btn-success my-2 mx-4" %>
      <%= link_to 'Cancel', common_pot_path, class: "btn btn-outline-danger my-2 mx-4" %>
    </div>
  <% end %>

</div>

app/views/events/show.html.erb
<div class="w-100 d-flex flex-column align-items-center">
  <h2 class="mb-3 heading-container">
    Event overview
    <span class="material-symbols-outlined heading-illustration-icons">
      search
    </span>
  </h2>

  <div class="p-4 rounded mb-4 d-flex flex-column align-items-center w-100 max-width-md position-relative border-dotted bg-white <%= @event.date < DateTime.current ? "border-info" : "border-secondary" %>">

    <% if @current_competition == @competition %>
      <div class="dropdown position-absolute top-0 end-0 me-2 mt-2">
        <i class="dropdown-toggle material-symbols-outlined" style="font-size:2rem !important" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          more_horiz
        </i>
        <ul class="dropdown-menu rounded-1 p-3 border-secondary" style="width: 200px">
          <li><%= link_to "Edit event", edit_event_path %></li>
        </ul>
      </div>
    <% end %>


    <div class="mb-4 text-center">
      <p class="fs-3 fw-bold"><%= @event.title %></p>
      <p>for <strong><%= @event.kid.name %></strong></p>
    </div>

    <div class="w-100 mb-3">
      <% if @event.content.blank? %>
        <p class="w-100 fst-italic mb-3">No additional info</p>
      <% else %>
        <p class="w-100 text-break mb-3"><%= @event.content %></p>
      <% end %>
    </div>

    <div class="my-3 d-flex flex-column align-items-center">
      <% if @event.user %>
        <p><span class="fw-bold fs-5"><%= @event.user == current_user ? "You" : @event.user.first_name.capitalize %></span></p>
        <p class="fs-5 ">picked the event</p>
      <% else %>
        <p class="fs-5 ">Nobody</p>
        <p class="fs-5 ">picked the event</p>
      <% end %>

      <% if @event.date < DateTime.current %>
        <p class="mt-3">This event is finished</p>
      <% else %>
        <% if @event.user == current_user %>
          <%= link_to "Unassign me the event", unassign_event_path(id: @event), class: "btn btn-outline-primary mt-3" %>
        <% elsif @event.user.nil? %>
          <%= link_to "Assign me the event", assign_event_path(id: @event), class: "btn btn-outline-primary mt-3" %>
        <% end %>
      <% end %>
    </div>


    <div class="d-flex flex-column align-items-center">
      <p class="mt-3">Date:</p>
      <p class="text-center"><%= @event.date.strftime "#{@event.date.day.ordinalize} %B %y at %H : %M" %></p>
    </div>
  </div>
</div>